### ISSUE TITLE
ECDSA 中的两个点 XY 数据是怎么获取出来的？

### ISSUE THREAD

**Issue by g302ge** [anonymous5l/mmtls#1]

**Comment by LeeMaster** [comment]
[](https://github.com/anonymous5l/mmtls/blob/768777758503333348fb90956f1deb4986c6d93f/mars/mmtls.go#L52)

**Comment by g302ge** [comment]
https://github.com/anonymous5l/mmtls/blob/768777758503333348fb90956f1deb4986c6d93f/mars/mmtls.go#L52

**Comment by anonymous5l** [comment]
这是内嵌在客户端的公钥作用验证服务器数据

**Comment by LeeMaster** [comment]
所以说这个公钥是被exposed 出来的吗？

**Comment by LeeMaster** [comment]
也是最近才开始接触逆向工程，leemast3r@gmail.com 老哥能给个联系方式交流一下子不？
